"""
Report generation endpoint.
Produces a structured clinical-style report for sharing with pediatricians.
"""

from __future__ import annotations

from datetime import date

from fastapi import APIRouter
from pydantic import BaseModel, Field

from models.norms import CDC_MILESTONES, get_closest_age_norm
from models.schemas import AssessmentResponse, ScoreLevel

router = APIRouter(prefix="/api/v1/report", tags=["report"])


class ReportRequest(BaseModel):
    child_id: str = ""
    child_age_months: int = Field(..., ge=0, le=60)
    assessments: list[AssessmentResponse]


class MilestoneChecklistItem(BaseModel):
    milestone: str
    domain: str
    expected: bool = True
    assessed: bool = False
    result: ScoreLevel | None = None


class ClinicalReport(BaseModel):
    report_date: str
    child_id: str
    child_age_months: int
    overall_score: ScoreLevel
    domain_scores: dict[str, ScoreLevel]
    milestone_checklist: list[MilestoneChecklistItem]
    feature_summary: dict[str, list[dict]]
    recommendations: list[str]
    disclaimer: str


@router.post("/generate", response_model=ClinicalReport)
async def generate_report(req: ReportRequest):
    domain_scores: dict[str, ScoreLevel] = {}
    feature_summary: dict[str, list[dict]] = {}
    recommendations: list[str] = []

    for assessment in req.assessments:
        domain = assessment.task_type.value
        domain_scores[domain] = assessment.score_level
        feature_summary[domain] = [
            {"name": f.name, "value": f.value, "unit": f.unit}
            for f in assessment.result.features
        ]
        if assessment.recommendation:
            recommendations.append(assessment.recommendation)

    # Overall score: worst across all domains
    if any(s == ScoreLevel.AT_RISK for s in domain_scores.values()):
        overall = ScoreLevel.AT_RISK
    elif any(s == ScoreLevel.BORDERLINE for s in domain_scores.values()):
        overall = ScoreLevel.BORDERLINE
    else:
        overall = ScoreLevel.NORMAL

    # CDC milestone checklist
    closest_age = min(CDC_MILESTONES.keys(), key=lambda a: abs(a - req.child_age_months))
    milestones = CDC_MILESTONES.get(closest_age, {})
    checklist = []
    for domain_name, items in milestones.items():
        for item in items:
            assessed = domain_name in domain_scores or any(
                domain_name in d for d in domain_scores
            )
            checklist.append(MilestoneChecklistItem(
                milestone=item,
                domain=domain_name,
                assessed=assessed,
                result=domain_scores.get(domain_name),
            ))

    return ClinicalReport(
        report_date=date.today().isoformat(),
        child_id=req.child_id,
        child_age_months=req.child_age_months,
        overall_score=overall,
        domain_scores=domain_scores,
        milestone_checklist=checklist,
        feature_summary=feature_summary,
        recommendations=recommendations,
        disclaimer=(
            "This report is generated by an AI-assisted developmental screening tool. "
            "It is NOT a clinical diagnosis. All results should be reviewed by a qualified "
            "pediatrician or developmental specialist. Classification decisions remain "
            "with the clinician based on comprehensive multi-dimensional assessment."
        ),
    )
